### ISSUE TITLE
How to setup Altserver on a raspberry pi 4B (64-bit/aarch64/arm64)

### ISSUE THREAD

**Issue by Macleykun** [hkfuertes/alt-server-wifi#6]
Hello!

I've tried using your docker-compose but i'm a bit confused how to properly run Altstore server really.

So my goal is to run Altstore-Server on my RPI so that if my PC is down, i can still refresh through wifi. Eventually i want to add a VPN so i can refresh from whatever place i am at.

Technically i don't plan to use the usb to refresh nor install any apps. However if the above works i would like to fiddle with that aswell :).

I look forward to your reply! I'm seriously impressed by your work :D

**Comment by hkfuertes** [comment]
First of all, this is not my work, hahahaha, this is just convenience docker scripts to build other's work... you can see in the readme the thanks section.
Secondly, I would suggest to build them separatelly, and then run the daemon, It will take a lot of time to build everything, that long time will be splitted into parts, and you will frustrate less, hahaha
so my bet will be:
```bash
# 1 build netmuxd
docker-compose run netmuxd
# 2 build altserver
docker-compose run altserver
# then run the manual step: First time requires a pair/wired refresh (run usbmuxd and then altserver)
docker-compose run config
# Then you can just bring up the daemon
docker-compose up -d daemon
```

**Comment by hkfuertes** [comment]
Else, you can create the `build` folder in the root of this project and put the binaries from the main repos there. This will prevent the `netmuxd` and/or `altserver` to be compiled, and daemon and config will run faster.

**Comment by Macleykun** [comment]
heya sorry for the really late reply!
I actuallyed talked with jkcoxson and currently wifi-refresh isn't working (maybe only for aarch64 but not sure).

Once that's done, i'll come back to you to ask if it's possible to supply the binairy itself, instead of compiling it.
That way, users only need to pull the image, one think i do wonder is when to enter the apple credentials. Currently i keep an eye here: https://github.com/powenn/AltServer-Linux-ShellScript/issues/43 to know when the binairies are useable for my usercase :).

Thank you for making these compose files! Can't wait to migrate to those after i figured it out with the shellscript :)

**Comment by Macleykun** [comment]
heya good news! the latest usbmuxd also supports wifi refresh
i sadly have to wait a few hours/days until i can use altstore to test this.

so this should now be possible which is great :D

**Comment by darderik** [comment]
> heya good news! the latest usbmuxd also supports wifi refresh i sadly have to wait a few hours/days until i can use altstore to test this.
> 
> so this should now be possible which is great :D

Are you sure about that? Would you mind pointing me to the usbmuxd changelog?

**Comment by Macleykun** [comment]
> > heya good news! the latest usbmuxd also supports wifi refresh i sadly have to wait a few hours/days until i can use altstore to test this.
> > so this should now be possible which is great :D
> 
> Are you sure about that? Would you mind pointing me to the usbmuxd changelog?

sorry i meant netmuxd!

**Comment by darderik** [comment]
> > > heya good news! the latest usbmuxd also supports wifi refresh i sadly have to wait a few hours/days until i can use altstore to test this.
> > > so this should now be possible which is great :D
> > 
> > 
> > Are you sure about that? Would you mind pointing me to the usbmuxd changelog?
> 
> sorry i meant netmuxd!

By the way, as it's still relevant to this issue, i adapted a bit the dockerfiles provided by hkfuertes and the whole setup seems to be working on Arm64. I may prepare a pull request. You can find the stuff on my fork. Be advised that it is pulling everything from github so it'll take a lot of time for having everything compiled

**Comment by Macleykun** [comment]
> > > > heya good news! the latest usbmuxd also supports wifi refresh i sadly have to wait a few hours/days until i can use altstore to test this.
> > > > so this should now be possible which is great :D
> > > 
> > > 
> > > Are you sure about that? Would you mind pointing me to the usbmuxd changelog?
> > 
> > 
> > sorry i meant netmuxd!
> 
> By the way, as it's still relevant to this issue, i adapted a bit the dockerfiles provided by hkfuertes and the whole setup seems to be working on Arm64. I may prepare a pull request. You can find the stuff on my fork. Be advised that it is pulling everything from github so it'll take a lot of time for having everything compiled

may i suggest (even withoud a ci/cd) to perhaps upload the builded images to dockerhub?
That makes it far easier for people to run it, as no compiling has to be done :)

see how: https://www.youtube.com/watch?v=HwATG0ygxzU
an example of me: https://github.com/mklements/OLED_Stats_Docker/blob/main/.github/workflows/publish.yml

edit: maybe i can add it into your fork later thisweek!

**Comment by Macleykun** [comment]
> > > > heya good news! the latest usbmuxd also supports wifi refresh i sadly have to wait a few hours/days until i can use altstore to test this.
> > > > so this should now be possible which is great :D
> > > 
> > > 
> > > Are you sure about that? Would you mind pointing me to the usbmuxd changelog?
> > 
> > 
> > sorry i meant netmuxd!
> 
> By the way, as it's still relevant to this issue, i adapted a bit the dockerfiles provided by hkfuertes and the whole setup seems to be working on Arm64. I may prepare a pull request. You can find the stuff on my fork. Be advised that it is pulling everything from github so it'll take a lot of time for having everything compiled

looks great! i see you also are hosting the images/pulling them which is great! If you want to improve the dockerfiles a bit you can use hadolint perhaps :)  https://hadolint.github.io/hadolint/

Just to be sure, how you setup the whole thing? Only using docker-compose up -d? how ya enter the apple id etc? and pair the device?

**Comment by darderik** [comment]
> > > > > heya good news! the latest usbmuxd also supports wifi refresh i sadly have to wait a few hours/days until i can use altstore to test this.
> 
> > > > > so this should now be possible which is great :D
> 
> > > > 
> 
> > > > 
> 
> > > > Are you sure about that? Would you mind pointing me to the usbmuxd changelog?
> 
> > > 
> 
> > > 
> 
> > > sorry i meant netmuxd!
> 
> > 
> 
> > By the way, as it's still relevant to this issue, i adapted a bit the dockerfiles provided by hkfuertes and the whole setup seems to be working on Arm64. I may prepare a pull request. You can find the stuff on my fork. Be advised that it is pulling everything from github so it'll take a lot of time for having everything compiled
> 
> 
> 
> looks great! i see you also are hosting the images/pulling them which is great! If you want to improve the dockerfiles a bit you can use hadolint perhaps :)  https://hadolint.github.io/hadolint/
> 
> 
> 
> Just to be sure, how you setup the whole thing? Only using docker-compose up -d? how ya enter the apple id etc? and pair the device?

Yeah I built the dockerfiles without worrying about the structure. I will clean them. I have to upload the usbmuxd image which is the biggest. I never entered my Apple ID, I bound the mobile phone with usbmuxd and ran altserver with compose up -d. Hit me up on my email on my profile so we can check if my stuff is actually working or not

**Comment by Macleykun** [comment]
> First of all, this is not my work, hahahaha, this is just convenience docker scripts to build other's work... you can see in the readme the thanks section. Secondly, I would suggest to build them separatelly, and then run the daemon, It will take a lot of time to build everything, that long time will be splitted into parts, and you will frustrate less, hahaha so my bet will be:
> 
> ```shell
> # 1 build netmuxd
> docker-compose run netmuxd
> # 2 build altserver
> docker-compose run altserver
> # then run the manual step: First time requires a pair/wired refresh (run usbmuxd and then altserver)
> docker-compose run config
> # Then you can just bring up the daemon
> docker-compose up -d daemon
> ```

so i've been trying to get it to work with these steps but i can't get altserver to stay running with yours, i eventually found out that your config container is meant to only pair. However shouldn't altserver be included in the container so that altstore can be installed?

I did get wifi-refresh to work with @darderik containers, but couldn't get the config container to work. If it's possible @hkfuertes  could you provide a more step by step approach?
Like clone this repo, do docker-compose xxx
this is meant for x and y, type in command --arg and if you get result you can exit.

I assume your compose is able to install altstore on a device and also do wifi refresh (and if you can update netmuxd, it should also wifi refresh for aarch64).

I do hope that's somewhat possible, as i can't figure it out with the readme/instructions as of now sadly

**Comment by webepg** [comment]
Guys, could you please provide a step by step tutorial on this? I tried to git clone all of your git repositories none of them does work. When running any of the docker compose commands the first command always fails. Then all the data gets pulled but nothing works. How did you even get one of these stacks to work? Aren't docker-compose packages supposed to just work when running the docker-compose up command? 

My system is an ARMBIAN (ARM64) one (https://github.com/ophub/amlogic-s9xxx-armbian)
